config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  devise_for :users
  resources :activities, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:create]
    resources :reviews, only: [:create]
  end

  namespace :owner do
    resources :bookings, only: :index
    # equivalent to => get '/<namespace>/bookings', to: '<namespace>/bookings#index'
  end
  resources :bookings, only: [:update, :index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :bookings
  has_many :reviews, dependent: :destroy
  belongs_to :user
  has_one_attached :photo

  validates :location, :hourly_rate, :description, presence: true

  def average_rating
    return 0 if reviews.nil? || reviews.empty?

    sum = 0
    reviews.each do |review|
      sum += review.rating
    end
    sum / reviews.length
  end

  include PgSearch::Model
  pg_search_scope :search_by_name,
  against: [ :name ],
  using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :activity

  validates :start_date, presence: true
  validates :end_date, presence: true

  enum status: { pending: 0, confirmed: 1, rejected: 2 }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :activity

  validates :rating, inclusion: { in: (0..5) }
  validates :comment, presence: true, length: { minimum: 3 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :activities
  has_many :bookings
  has_one_attached :photo
  has_many :bookings_as_owner, through: :activities, source: :bookings
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @activities = if params[:query].present?
      Activity.search_by_name(params[:query])
    else
      Activity.all
    end
    @no_activities_found = @activities.empty?

    @activity = Activity.new
  end

  def show
    @activity = Activity.find(params[:id])
    @review = Review.new
    @booking = Booking.new
  end

  # def new
  #   @activity = Activity.new
  # end

  def create
    @activity = Activity.new(activity_params)
    @activity.user = current_user

    if @activity.save
      redirect_to activity_path(@activity)
    else
      render partial: 'create_activity', layout: false
    end
  end

  private

  def activity_params
    params.require(:activity).permit(:name, :location, :description, :hourly_rate, :photo)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_activity, only: [:create]

  def index
    @bookings = Booking.where(user: current_user)
    @bookings_as_owner = current_user.bookings_as_owner
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.activity = @activity
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path(@booking)
    else
      render 'activities/show', status: :unprocessable_entity
    end
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to bookings_path, notice: "Booking status updated successfully."
    else
      render :index, status: :unprocessable_entity
    end
  end

  private

  def set_activity
    @activity = Activity.find(params[:activity_id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :user_id, :activity_id, :status)
  end
end

app/controllers/owner/bookings_controller.rb
class Owner::BookingsController < ApplicationController
  def index
    @bookings = current_user.bookings_as_owner
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  def home
    @activity = Activity.new
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_activity, only: [:create]

  def create
    @review = Review.new(review_params)
    @review.activity = @activity
    if @review.save
      redirect_to activity_path(@activity)
    else
      render 'activities/show', status: :unprocessable_entity
    end
  end

  private

  def set_activity
    @activity = Activity.find(params[:activity_id])
  end

  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/_act_show.html.erb
<% if @activity.photo.attached? %>
  <%= cl_image_tag @activity.photo.key, class: 'activity-image' %>
<% else %>
  <%= image_tag 'sunset.jpg' %>
<% end %>
<div class="activity-details bg-white text-dark">
    <h1 class="title"><strong><%= @activity.name %></strong></h1>
    <p class="description"><%= @activity.description %></p>
    <p class="location">Location: <%= @activity.location %></p>
    <p class="hourly-rate">¥<%= @activity.hourly_rate %>/hour</p>
</div>

app/views/activities/_card.html.erb
<div class="card card-trip">
  <%= cl_image_tag activity.photo.key if activity.photo.attached? %>
  <div class="card-trip-infos">
    <div>
      <p class="activity-location"><i class="fas fa-map-marker-alt"></i> <%= activity.location %></p>
      <h5 class="activity-title"><%= activity.name %></h5>
      <p class="activity-description mb-3"><%= activity.description %></p>
      <div class="d-flex align-items-center">
        <h2 class="card-trip-pricing">¥<%= activity.hourly_rate %></h2>
        <p class="card-text"> /per hour</p>
      </div>
    </div>
    <div class="d-flex align-items-center justify-content-end">
      <% if activity.user.photo.attached? %>
        <%= cl_image_tag activity.user.photo.key, class: "card-trip-user avatar-bordered rounded-circle mr-2" %>
      <% end %>
      <% if activity.user.first_name.present? %>
        <h3 class="card-trip-user-name mb-0"><%= activity.user.first_name %></h3>
      <% end %>
    </div>
  </div>
  <%= link_to "", activity_path(activity), class: "stretched-link card-link" %>
</div>

app/views/activities/_create_activity.html.erb
<div class="col-12 col-sm-12 col-md-4 col-lg-4 col-xl-3 col-xxl-3 card bg-light sticky-top">
  <h1>add a new activity</h1>
  <%= simple_form_for @activity do |f| %>
    <% if @activity.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>
        <ul>
          <% @activity.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.input :name, required: true %>
    <%= f.input :location, required: true %>
    <%= f.input :description, required: true %>
    <%= f.input :hourly_rate, required: true %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, "post your activity!" %>
  <% end %>
</div>

app/views/activities/_user_card.html.erb
<div class="profile-card">
  <div class="d-flex">
    <div class="profile-image">
      <% if @activity.user.photo.attached? %>
        <%= cl_image_tag @activity.user.photo.key %>
      <% else %>
        <%= image_tag 'user_profile.avif' %>
      <% end %>
    </div>
    <div class="profile-details">
      <% if @activity.user.first_name.present? && @activity.user.gender.present? && @activity.user.age.present?%>
        <h2><%= @activity.user.first_name %> ・ <%= @activity.user.age %></h2>
        <p><%= @activity.user.gender %></p>
      <% else %>
        <h2><%= @activity.user.username %></h2>
      <% end %>
    </div>
  </div>
  <div class="rating">
    <% @activity.average_rating.times do %>
      <i class="fa-solid fa-star" style="color: #ffde0a;"></i>
    <% end %>
    <% (5 - @activity.average_rating).times do %>
      <i class="fa-regular fa-star" style="color: #ffde0a;"></i>
    <% end %>
  </div>
</div>

app/views/activities/index.html.erb
<div class="container mt-4">
  <div class="d-flex justify-content-between align-items-center">
    <%= link_to new_activity_path, class: 'text-dark text-decoration-none' do %>
    <% end %>
  </div>
  <header class="text-center mb-5">
    <h1 class="display-4 font-weight-bold">Explore Available Activities</h1>
    <p class="font-italic text-muted mb-0">Discover and rent your next exciting adventure!</p>
  </header>

  <% if @no_activities_found %>
    <p class="text-center" style="color: purple">No activities found. How about creating your own? <%= render 'activities/create_activity' %></p>
  <% else %>
    <h2 class="font-weight-bold mb-2">Featured Activities</h2>
    <p class="font-italic text-muted mb-4">Find your perfect rental experience from our curated collection.</p>
    <div class="cards">
      <% @activities.each do |activity| %>
        <%= render 'activities/card', activity: activity %>
      <% end %>

    </div>
    <p class="text-center" style="color: purple">How about creating your own? <%= render 'activities/create_activity' %></p>
  <% end %>
</div>

app/views/activities/show.html.erb
<div class="container">
    <div class="d-flex flex-row">
      <div class="activity col-8 bg-white">
          <%= render "activities/act_show" %>
      </div>
      <div class="user-forms d-flex flex-column col-4 mx-4">
        <%= render "activities/user_card" %>

        <div class="activity-card bg-white">
          <h4>Booking</h4>
          <% if user_signed_in? %>
            <%= render 'bookings/form', booking: Booking.new %>
          <% else %>
            <p>Please <%= link_to "sign in", new_user_session_path %> to make a booking.</p>
          <% end %>
        </div>

        <div class="activity-card bg-white">
          <h4>Leave a review for <%= @activity.user.first_name %></h4>
          <% if user_signed_in? %>
            <%= render 'reviews/formr', review: Review.new %>
          <% else %>
            <p>Please <%= link_to "sign in", new_user_session_path %> to leave a review.</p>
          <% end%>
        </div>
      </div>
    </div>

    <div class="reviews">
      <h2><%= @activity.user.first_name %> 's reviews </h2>
      <% if @activity.reviews.present? %>
      <ul class="list-group">
        <% @activity.reviews.each do |review| %>
          <li class="list-group-item"><%= review.comment.strip %></li>
        <% end %>
      </ul>
      <% else %>
        <p>No reviews yet!</p>
      <% end %>
    </div>
  <%= link_to "Back to activities", activities_path, class: "button-link" %>
</div>

app/views/bookings/_booking_card.html.erb
<%= render "bookings/booking_card_info", booking: booking %>

app/views/bookings/_booking_card_info.html.erb
<div class="button-show">
<div class="p-1 m-2"><p class="text-end pe-3 booking-color-<%=booking.status%>" style="margin: 0;"><strong><%= booking.status.capitalize %></strong></p>
  <div class="card bg-white rounded-4 booking-border-<%=booking.status%>" style="width: 25rem; height: 18rem;">
    <div class="pt-3 ps-3 pe-3">
      <div class="d-inline-flex">
          <div class="profile-image">
            <%= cl_image_tag booking.activity.user.photo.key if booking.activity.user.photo.attached?%>
          </div>
      <h3><strong><%= booking.activity.name %></strong> with <%= booking.activity.user.first_name%> on <%= booking.start_date.strftime('%B %d') %> </h3>
      </div>
      <div class="d-inline-flex">
        <i class="fa-solid fa-map-pin"></i>
        <p class="ms-2"><%= booking.activity.location %></p>

        <p class="ps-5">Start: <%=booking.start_date %><br>End: <%= booking.end_date %></p>
      </div>
      <hr class="dropdown-divider">
      <p class="pt-1"><%= booking.activity.description %></p>
      </div>
      <% if booking.user != current_user %>
      <%= render "bookings/booking_update_form", booking: booking %>
      <% end %>
  </div>
</div>
</div>

app/views/bookings/_booking_update_form.html.erb
<% if booking.pending? %>
  <div class="card-footer hide-button">
    <%= simple_form_for booking do |f| %>
      <%= f.input :status, as: :hidden, input_html:{value: "confirmed"} %>
      <%= f.submit "Accept", class: "btn btn-success" %>
    <% end %>
    <%= simple_form_for booking do |f| %>
      <%= f.input :status, as: :hidden, input_html:{value: "rejected"} %>
      <%= f.submit "Reject", class: "btn btn-danger" %>
    <% end %>
  </div>
<% end %>

app/views/bookings/_form.html.erb
<%= simple_form_for [@activity, booking] do |f| %>
  <%= f.input :start_date, html5: true %>
  <%= f.input :end_date, html5: true %>
  <%= f.submit "Request Booking", class: "button-link" %>
<% end %>

app/views/bookings/index.html.erb
<div class="container">
  <div class="d-flex flex-row align-items-baseline justify-content-between">
    <h1>Your Bookings | <%= link_to "Requests for You", owner_bookings_path%></h1>
    <%= link_to "Back to search", activities_path, class: "p-3" %>
  </div>

      <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
        <li class="nav-item" role="presentation">
          <button class="nav-link active" id="pills-all-tab" data-bs-toggle="pill" data-bs-target="#pills-all" type="button" role="tab" aria-controls="pills-all" aria-selected="true">All</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="pills-confirmed-tab" data-bs-toggle="pill" data-bs-target="#pills-confirmed" type="button" role="tab" aria-controls="pills-confirmed" aria-selected="false">Confirmed</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="pills-rejected-tab" data-bs-toggle="pill" data-bs-target="#pills-rejected" type="button" role="tab" aria-controls="pills-rejected" aria-selected="false">Rejected</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="pills-pending-tab" data-bs-toggle="pill" data-bs-target="#pills-pending" type="button" role="tab" aria-controls="pills-pending" aria-selected="false">Pending</button>
        </li>
      </ul>


      <div class="tab-content" id="pills-tabContent">
        <div class="tab-pane fade show active" id="pills-all" role="tabpanel" aria-labelledby="pills-all-tab" tabindex="0">

            <div class="d-flex flex-row flex-wrap">

              <% @bookings.each do |booking|  %>
                <%=  render "/bookings/booking_card", booking: booking %>
              <% end %>
            </div>


          </div>

        <div class="tab-pane fade" id="pills-confirmed" role="tabpanel" aria-labelledby="pills-confirmed-tab" tabindex="0">

          <div class="d-flex flex-row flex-wrap">

              <% @bookings.where(status: 'confirmed').each do |booking|  %>
                  <%=  render "/bookings/booking_card", booking: booking %>
              <% end %>

          </div>
        </div>

        <div class="tab-pane fade" id="pills-rejected" role="tabpanel" aria-labelledby="pills-rejected-tab" tabindex="0">

            <div class="d-flex flex-row flex-wrap">

                  <% @bookings.where(status: 'rejected').each do |booking|  %>
                    <%=  render "/bookings/booking_card", booking: booking %>
                  <% end %>

            </div>

        </div>

        <div class="tab-pane fade" id="pills-pending" role="tabpanel" aria-labelledby="pills-pending-tab" tabindex="0">

            <div class="d-flex flex-row flex-wrap">

                <% @bookings.where(status: 'pending').each do |booking|  %>
                  <%=  render "/bookings/booking_card", booking: booking %>
                <% end %>

            </div>

          </div>
        </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "Buddyアップ", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link mx-2" %>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.photo.attached? %>
                <%= cl_image_tag current_user.photo.key, class: "avatar", alt: "dropdown menu"%>
              <% else %>
                <%= image_tag "profile.png", class: "avatar", alt: "dropdown menu" %>
              <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Search", activities_path, class: "dropdown-item" %>
              <%= link_to "Bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "yellow-button" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BuddyUp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
  <%= render "layouts/navbar" %>
  <%= render "shared/flashes" %>

    <%= yield %>
    <div class="footer">
      <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
      <div class="footer-copyright">
        © 2023 Buddyアップ, Inc <i class="fas fa-heart"></i>
      </div>
    </div>
  </body>
</html>

app/views/owner/bookings/index.html.erb
<div class="container">
  <div class="d-flex flex-row align-items-baseline justify-content-between">
    <h1><%= link_to "Your Bookings", bookings_path%> | Requests for You</h1>
    <%= link_to "Back to search", activities_path, class: "p-3" %>
  </div>

      <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
        <li class="nav-item" role="presentation">
          <button class="nav-link active" id="pills-all-tab" data-bs-toggle="pill" data-bs-target="#pills-all" type="button" role="tab" aria-controls="pills-all" aria-selected="true">All</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="pills-confirmed-tab" data-bs-toggle="pill" data-bs-target="#pills-confirmed" type="button" role="tab" aria-controls="pills-confirmed" aria-selected="false">Confirmed</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="pills-rejected-tab" data-bs-toggle="pill" data-bs-target="#pills-rejected" type="button" role="tab" aria-controls="pills-rejected" aria-selected="false">Rejected</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="pills-pending-tab" data-bs-toggle="pill" data-bs-target="#pills-pending" type="button" role="tab" aria-controls="pills-pending" aria-selected="false">Pending</button>
        </li>
      </ul>


      <div class="tab-content" id="pills-tabContent">
        <div class="tab-pane fade show active" id="pills-all" role="tabpanel" aria-labelledby="pills-all-tab" tabindex="0">

            <div class="d-flex flex-row flex-wrap">

              <% @bookings.each do |booking|  %>
                <%=  render "/bookings/booking_card", booking: booking %>
              <% end %>
            </div>


          </div>

        <div class="tab-pane fade" id="pills-confirmed" role="tabpanel" aria-labelledby="pills-confirmed-tab" tabindex="0">

          <div class="d-flex flex-row flex-wrap">

              <% @bookings.where(status: 'confirmed').each do |booking|  %>
                  <%=  render "/bookings/booking_card", booking: booking %>
              <% end %>

          </div>
        </div>

        <div class="tab-pane fade" id="pills-rejected" role="tabpanel" aria-labelledby="pills-rejected-tab" tabindex="0">

            <div class="d-flex flex-row flex-wrap">

                  <% @bookings.where(status: 'rejected').each do |booking|  %>
                    <%=  render "/bookings/booking_card", booking: booking %>
                  <% end %>

            </div>

        </div>

        <div class="tab-pane fade" id="pills-pending" role="tabpanel" aria-labelledby="pills-pending-tab" tabindex="0">

            <div class="d-flex flex-row flex-wrap">

                <% @bookings.where(status: 'pending').each do |booking|  %>
                  <%=  render "/bookings/booking_card", booking: booking %>
                <% end %>

            </div>

          </div>
        </div>
</div>

</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path "hiking.jpg" %>);">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8 text-center">
        <h1>Buddyアップ</h1>
        <h3 class="sub-banner">Find new friends through your favorite hobbies, sports, and games!</h3>
        <form action="<%= activities_path %>" method="GET">
          <div class="input-group">
            <input class="form-control small-search-input" type="search" placeholder="Skateboarding, billiards, poetry..." aria-label="Search" name="query">
            <button class="btn button-link" type="submit">go!</button>
          </div>
        </form>
        <a href="#how-it-works-section" class="btn yellow-button mt-3">how buddyアップ works</a>
      </div>
    </div>
  </div>
</div>
</div>
</div>
<div  class="container-fluid mt-4" style="background-color: #E1EFE6; padding-left: 15px; padding-bottom: 15px;">
  <div class="row justify-content-center">
    <div class="col-md-10 pt-5 text-center">
      <h1>How it works</h1>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2 class="text-center">Use the search bar to find an activity to try</h2>
      <form action="<%= activities_path %>" method="GET">
        <div class="input-group">
          <input class="form-control small-search-input" type="search" placeholder="Skateboarding, billiards, poetry..." aria-label="Search" name="query">
          <button class="btn button-link" type="submit">go!</button>
        </div>
      </div>
      <div id="how-it-works-section" class="col-md-6 d-flex justify-content-center align-items-center">
        <%= image_tag('activity1.jpg', alt: 'Image1', style: 'max-width: 400px; height: auto; border-radius: 10px;') %>
      </div>
    </div>
    <div class="row justify-content-center mt-4">
      <div class="col-md-6 d-flex justify-content-center align-items-center">
        <%= image_tag('activity2.jpg', alt: 'Image 2', style: 'max-width: 400px; height: auto; border-radius: 10px;') %>
      </div>
      <div class="col-md-6 text-center d-flex justify-content-center align-items-center">
        <h2 class="m-0">...or <a href="<%= activities_path %>" class="text-decoration-none">browse all the fun</a>.</h2>
      </div>
    </div>
    <div class="row justify-content-center mt-4">
      <div class="col-md-6 text-center d-flex justify-content-center align-items-center">
        <h2 class="m-0">Find something cool? <a href="<%= new_user_registration_path %>" class="text-decoration-none">create an account</a> and <a href="<%= new_user_session_path %>" class="text-decoration-none">login!</a></h2>
      </div>
      <div class="col-md-6 d-flex justify-content-center align-items-center">
        <%= image_tag('activity3.jpg', alt: 'Image 3', style: 'max-width: 400px; height: auto; border-radius: 10px;') %>
      </div>
    </div>
  </div>

app/views/reviews/_form.html.erb
<%= simple_form_for [@activity, review] do |f| %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.input :comment %>
  <%= f.submit "Add review" %>
<% end %>

app/views/reviews/_formr.html.erb
<%= simple_form_for [@activity, review] do |f| %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.input :comment %>
  <%= f.submit "Add review", class: "button-link" %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>